name: u_search_flutter
description: A new Fxtter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  app_ui:
    path: ./packages/app_ui
  application_repository:
    path: ./packages/application_repository
  bloc: ^8.1.2
  bloc_test: ^9.1.5
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_core: ^2.27.2
  firebase_auth: ^4.3.0
  firebase_dart_flutter: ^1.1.3
  firebase_crashlytics: ^3.4.20
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  form_inputs:
    path: ./packages/form_inputs
  freezed_annotation: ^2.4.1
  go_router: ^12.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  mocktail: ^1.0.1
  package_info_client:
    path: ./packages/package_info_client
  persistent_storage:
    path: ./packages/storage/persistent_storage
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  token_storage:
    path: ./packages/token_storage
  user_repository:
    path: ./packages/user_repository
  u_search_api:
    path: ./api
  provider: ^6.1.2
  bloc_concurrency: ^0.2.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
