name: firebase_authentication_client
description: An Firebase Authentication Interface
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client
  equatable: ^2.0.5

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
