// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZAK0VmmCRvZpa3ECViVNxAPeTbc1blvY',
    appId: '1:435922298456:web:942d80fa6ddb8cd85b8c2d',
    messagingSenderId: '435922298456',
    projectId: 'usearch-5d952',
    authDomain: 'usearch-5d952.firebaseapp.com',
    storageBucket: 'usearch-5d952.appspot.com',
    measurementId: 'G-3KJF68FTD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcnU1d6Db_OZ24ejnA0qorssi2BRqA0vg',
    appId: '1:435922298456:android:a099d4af838fd1fb5b8c2d',
    messagingSenderId: '435922298456',
    projectId: 'usearch-5d952',
    storageBucket: 'usearch-5d952.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk2pB7wYwV_yNSKdPqhfTFqZLGumBiBSk',
    appId: '1:435922298456:ios:b57faa704454b2395b8c2d',
    messagingSenderId: '435922298456',
    projectId: 'usearch-5d952',
    storageBucket: 'usearch-5d952.appspot.com',
    iosBundleId: 'com.example.uSearchFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk2pB7wYwV_yNSKdPqhfTFqZLGumBiBSk',
    appId: '1:435922298456:ios:08b49da42fcc53e15b8c2d',
    messagingSenderId: '435922298456',
    projectId: 'usearch-5d952',
    storageBucket: 'usearch-5d952.appspot.com',
    iosBundleId: 'com.example.uSearchFlutter.RunnerTests',
  );
}
