name: u_search_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.3.3
  equatable: ^2.0.5
  formz: ^0.6.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  coverage: ^1.7.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
