name: u_search_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  equatable: ^2.0.5
  http: ^1.2.1
  json_annotation: ^4.6.0
  logging: ^1.2.0
  path: ^1.8.0
  uuid: ^4.4.0
  my_sql_client:
    path: packages/my_sql_client
  email_service:
    path: packages/email_service
  app_domain:
    path: packages/app_domain
  dart_frog_auth: ^1.1.0
  shelf_cors_headers: ^0.1.5
  dotenv: ^4.2.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
